apiVersion: v1
kind: DeploymentConfig
metadata:
  name: omar-mapproxy
  namespace: omar-dev
  selfLink: /oapi/v1/namespaces/omar-dev/deploymentconfigs/omar-mapproxy
  uid: feb04032-949c-11e7-ba3b-0e704fd9c8b2
  resourceVersion: '8870071'
  generation: 64
  creationTimestamp: '2017-09-08T13:52:46Z'
  labels:
    app: omar-mapproxy
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - omar-mapproxy
        from:
          kind: ImageStreamTag
          namespace: o2
          name: 'omar-mapproxy:latest'
        lastTriggeredImage: >-
          172.30.181.173:5000/o2/omar-mapproxy@sha256:c9aab50acbd2b1db1ae7abbe39002fa5dd581b16a606382ff27f8d3712c234a2
  replicas: 1
  test: false
  selector:
    app: omar-mapproxy
    deploymentconfig: omar-mapproxy
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: omar-mapproxy
        deploymentconfig: omar-mapproxy
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      volumes:
        - name: volume-0693w
          persistentVolumeClaim:
            claimName: basemap-cache-dev-pvc
      containers:
        - name: omar-mapproxy
          image: >-
            172.30.181.173:5000/o2/omar-mapproxy@sha256:c9aab50acbd2b1db1ae7abbe39002fa5dd581b16a606382ff27f8d3712c234a2
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: volume-0693w
              mountPath: /mapproxy
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
status:
  latestVersion: 61
  observedGeneration: 64
  replicas: 1
  updatedReplicas: 1
  availableReplicas: 1
  unavailableReplicas: 0
  details:
    message: image change
    causes:
      - type: ImageChange
        imageTrigger:
          from:
            kind: ImageStreamTag
            namespace: o2
            name: 'omar-mapproxy:latest'
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2017-10-31T19:43:06Z'
      lastTransitionTime: '2017-10-31T19:43:06Z'
      message: Deployment config has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2017-11-30T14:34:32Z'
      lastTransitionTime: '2017-11-30T14:34:31Z'
      reason: NewReplicationControllerAvailable
      message: replication controller "omar-mapproxy-61" successfully rolled out
  readyReplicas: 1
